### ISSUE TITLE
フォローの確認をするapiの変更 #7

### ISSUE THREAD

**Issue by akakou** [makino-makino/neo-panopticon-api#11]
/followings/?from_id=1&to_id=2 のような形で、（配列を）取得できるように変更してくれるとうれしいです。

**Comment by akakou** [comment]
`feature/following`

**Comment by kino-ma** [comment]
多分できたような気がするけど実際に動かさないことには何とも言えない

**Comment by akakou** [comment]
https://github.com/makino-makino/neo-panopticon-api/commit/f74267535e250eb9899b5ca790cdddfff06f7c29
